# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-08 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default=b'none', max_length=100)),
                ('barcode', models.IntegerField(default=0)),
                ('role', models.CharField(choices=[(b'TE', b'test engineer'), (b'OP', b'operator')], default=b'none', max_length=100)),
            ],
        ),
    ]
